---
# tasks file for install_lets_encrypt
- name: disable_system_repo in /etc/dnf/plugins/subscirption-manager.conf
  # Content suggestion provided by Ansible Lightspeed
  ansible.builtin.lineinfile:
    path: /etc/dnf/plugins/subscription-manager.conf
    regexp: ^disable_system_repo
    line: disable_system_repo=0

- name: Install EPEL for RHEL 8 repository
  dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
    state: present
    disable_gpg_check: true

- name: Install snapd package
  dnf:
    name: snapd
    state: present
  notify: Enable and start snapd socket

- name: Flush handlers manually
  meta: flush_handlers

- name: Create symbolic link for snap
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  notify: Reboot the system

- name: Flush handlers manually
  meta: flush_handlers

- name: Install/Refresh core snap
  community.general.snap:
    name: core
    state: present

- name: Install certbot classic snap
  community.general.snap:
    name: certbot
    classic: yes

- name: Create symbolic link for certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Obtain SSL certificate using certbot and nginx
  command: sudo certbot certonly --nginx -d $(hostname) --non-interactive --agree-tos --email mbredeme@redhat.com
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Test certbot renewal in dry-run mode
  command: certbot renew --dry-run 
  environment:
    PATH: "{{ ansible_env.PATH }}"

